### ISSUE TITLE
Autonomous Drivetrain Motion - Vision

### ISSUE THREAD

**Issue by LeviWalker** [NASAKnights/InfiniteRecharge#16]
The drivetrain needs to be calibrated and have basic autonomous routines.

**Comment by bhooten** [comment]
Assigning both @LeviWalker and @signalxp to this due to the cooperative nature of implementing this. Please post any pertinent information relating to this here.

**Comment by bhooten** [comment]
Will be adjusting this title for better specificity.

**Comment by bhooten** [comment]
Realized this is a duplicate issue... please view issue #9.
